// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_calculate_covariance_allier
SEXP cpp_calculate_covariance_allier(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_allier(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_allier(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_RIL_allier
SEXP cpp_calculate_covariance_RIL_allier(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_RIL_allier(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_RIL_allier(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_lehermeier
SEXP cpp_calculate_covariance_lehermeier(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_lehermeier(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_lehermeier(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_RIL_lehermeier
SEXP cpp_calculate_covariance_RIL_lehermeier(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_RIL_lehermeier(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_RIL_lehermeier(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_osthushenrich
SEXP cpp_calculate_covariance_osthushenrich(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_osthushenrich(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_osthushenrich(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_RIL_osthushenrich
SEXP cpp_calculate_covariance_RIL_osthushenrich(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& M, const NumericMatrix& U, double t, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_RIL_osthushenrich(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP MSEXP, SEXP USEXP, SEXP tSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_RIL_osthushenrich(Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_covariance_wolfe
SEXP cpp_calculate_covariance_wolfe(const NumericMatrix& Crosses, const List& genMap, const NumericMatrix& Hap1, const NumericMatrix& Hap2, const NumericMatrix& U, const NumericMatrix& D, double intensity, const NumericVector& weights, bool covariance, bool calcindex, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_covariance_wolfe(SEXP CrossesSEXP, SEXP genMapSEXP, SEXP Hap1SEXP, SEXP Hap2SEXP, SEXP USEXP, SEXP DSEXP, SEXP intensitySEXP, SEXP weightsSEXP, SEXP covarianceSEXP, SEXP calcindexSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type genMap(genMapSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Hap1(Hap1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Hap2(Hap2SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< bool >::type calcindex(calcindexSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_covariance_wolfe(Crosses, genMap, Hap1, Hap2, U, D, intensity, weights, covariance, calcindex, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calcOHV
DataFrame cpp_calcOHV(const NumericMatrix& Crosses, const List& HBlocks, const NumericMatrix& M, const NumericVector& mu_vec, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calcOHV(SEXP CrossesSEXP, SEXP HBlocksSEXP, SEXP MSEXP, SEXP mu_vecSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const List& >::type HBlocks(HBlocksSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu_vec(mu_vecSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calcOHV(Crosses, HBlocks, M, mu_vec, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_desired_gains
SEXP cpp_calculate_desired_gains(const NumericMatrix& A, const NumericMatrix& V, const NumericMatrix& approxV, const NumericVector& gains, bool useMargV, bool useV, bool useapproxV, int nThreads);
RcppExport SEXP _CrossingTools_cpp_calculate_desired_gains(SEXP ASEXP, SEXP VSEXP, SEXP approxVSEXP, SEXP gainsSEXP, SEXP useMargVSEXP, SEXP useVSEXP, SEXP useapproxVSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type approxV(approxVSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gains(gainsSEXP);
    Rcpp::traits::input_parameter< bool >::type useMargV(useMargVSEXP);
    Rcpp::traits::input_parameter< bool >::type useV(useVSEXP);
    Rcpp::traits::input_parameter< bool >::type useapproxV(useapproxVSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_desired_gains(A, V, approxV, gains, useMargV, useV, useapproxV, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_u_from_from_g
SEXP cpp_u_from_from_g(const NumericMatrix& M, const NumericMatrix& G, const NumericMatrix& g, double scalingFactor, double tol, bool LDvar, const Nullable<DataFrame>& Grouping, bool calcPriorVcov, const Nullable<NumericMatrix> PriorVcov, const Nullable<NumericMatrix> sigmasq, bool calcPosteriorVcov, const Nullable<NumericMatrix> PEV, int nThreads);
RcppExport SEXP _CrossingTools_cpp_u_from_from_g(SEXP MSEXP, SEXP GSEXP, SEXP gSEXP, SEXP scalingFactorSEXP, SEXP tolSEXP, SEXP LDvarSEXP, SEXP GroupingSEXP, SEXP calcPriorVcovSEXP, SEXP PriorVcovSEXP, SEXP sigmasqSEXP, SEXP calcPosteriorVcovSEXP, SEXP PEVSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type scalingFactor(scalingFactorSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type LDvar(LDvarSEXP);
    Rcpp::traits::input_parameter< const Nullable<DataFrame>& >::type Grouping(GroupingSEXP);
    Rcpp::traits::input_parameter< bool >::type calcPriorVcov(calcPriorVcovSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix> >::type PriorVcov(PriorVcovSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix> >::type sigmasq(sigmasqSEXP);
    Rcpp::traits::input_parameter< bool >::type calcPosteriorVcov(calcPosteriorVcovSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix> >::type PEV(PEVSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_u_from_from_g(M, G, g, scalingFactor, tol, LDvar, Grouping, calcPriorVcov, PriorVcov, sigmasq, calcPosteriorVcov, PEV, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_optimal_cross_selection
Rcpp::List cpp_optimal_cross_selection(const NumericMatrix& Crosses, const NumericMatrix& fixedCrosses, arma::uword nCross, double targetAngle, arma::vec& u, arma::vec& ufixed, arma::mat& G, double probMut, arma::uword nMutate, arma::uword nSel, arma::uword nPop, arma::uword maxGen, arma::uword maxRun, double anglePenalty, int nThreads);
RcppExport SEXP _CrossingTools_cpp_optimal_cross_selection(SEXP CrossesSEXP, SEXP fixedCrossesSEXP, SEXP nCrossSEXP, SEXP targetAngleSEXP, SEXP uSEXP, SEXP ufixedSEXP, SEXP GSEXP, SEXP probMutSEXP, SEXP nMutateSEXP, SEXP nSelSEXP, SEXP nPopSEXP, SEXP maxGenSEXP, SEXP maxRunSEXP, SEXP anglePenaltySEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Crosses(CrossesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type fixedCrosses(fixedCrossesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nCross(nCrossSEXP);
    Rcpp::traits::input_parameter< double >::type targetAngle(targetAngleSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type ufixed(ufixedSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type probMut(probMutSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nMutate(nMutateSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nSel(nSelSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nPop(nPopSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxGen(maxGenSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxRun(maxRunSEXP);
    Rcpp::traits::input_parameter< double >::type anglePenalty(anglePenaltySEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_optimal_cross_selection(Crosses, fixedCrosses, nCross, targetAngle, u, ufixed, G, probMut, nMutate, nSel, nPop, maxGen, maxRun, anglePenalty, nThreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CrossingTools_cpp_calculate_covariance_allier", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_allier, 10},
    {"_CrossingTools_cpp_calculate_covariance_RIL_allier", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_RIL_allier, 10},
    {"_CrossingTools_cpp_calculate_covariance_lehermeier", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_lehermeier, 10},
    {"_CrossingTools_cpp_calculate_covariance_RIL_lehermeier", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_RIL_lehermeier, 10},
    {"_CrossingTools_cpp_calculate_covariance_osthushenrich", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_osthushenrich, 10},
    {"_CrossingTools_cpp_calculate_covariance_RIL_osthushenrich", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_RIL_osthushenrich, 10},
    {"_CrossingTools_cpp_calculate_covariance_wolfe", (DL_FUNC) &_CrossingTools_cpp_calculate_covariance_wolfe, 11},
    {"_CrossingTools_cpp_calcOHV", (DL_FUNC) &_CrossingTools_cpp_calcOHV, 5},
    {"_CrossingTools_cpp_calculate_desired_gains", (DL_FUNC) &_CrossingTools_cpp_calculate_desired_gains, 8},
    {"_CrossingTools_cpp_u_from_from_g", (DL_FUNC) &_CrossingTools_cpp_u_from_from_g, 13},
    {"_CrossingTools_cpp_optimal_cross_selection", (DL_FUNC) &_CrossingTools_cpp_optimal_cross_selection, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_CrossingTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
