# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calculate_covariance_allier <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_allier`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_RIL_allier <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_RIL_allier`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_lehermeier <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_lehermeier`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_RIL_lehermeier <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_RIL_lehermeier`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_osthushenrich <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_osthushenrich`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_RIL_osthushenrich <- function(Crosses, genMap, M, U, t, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_RIL_osthushenrich`, Crosses, genMap, M, U, t, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calculate_covariance_wolfe <- function(Crosses, genMap, Hap1, Hap2, U, D, intensity, weights, covariance = FALSE, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_wolfe`, Crosses, genMap, Hap1, Hap2, U, D, intensity, weights, covariance, calcindex, nThreads)
}

cpp_calcOHV <- function(Crosses, HBlocks, M, mu_vec, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calcOHV`, Crosses, HBlocks, M, mu_vec, nThreads)
}

cpp_calcOHV4W <- function(Crosses, HBlocks, M, mu_vec, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calcOHV4W`, Crosses, HBlocks, M, mu_vec, nThreads)
}

cpp_calculate_expectation_A <- function(Crosses, M, U, weights, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_expectation_A`, Crosses, M, U, weights, calcindex, nThreads)
}

cpp_calculate_expectation_A4W <- function(Crosses, M, U, weights, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_expectation_A4W`, Crosses, M, U, weights, calcindex, nThreads)
}

cpp_calculate_expectation_AD <- function(Crosses, Hap1, Hap2, U, D, weights, calcindex = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_expectation_AD`, Crosses, Hap1, Hap2, U, D, weights, calcindex, nThreads)
}

cpp_calculate_desired_gains <- function(A, V, approxV, gains, useMargV = FALSE, useV = FALSE, useapproxV = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_desired_gains`, A, V, approxV, gains, useMargV, useV, useapproxV, nThreads)
}

cpp_u_from_from_g <- function(M, G, g, scalingFactor, tol = 1e-10, LDvar = FALSE, Grouping = NULL, calcPriorVcov = FALSE, PriorVcov = NULL, sigmasq = NULL, calcPosteriorVcov = FALSE, PEV = NULL, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_u_from_from_g`, M, G, g, scalingFactor, tol, LDvar, Grouping, calcPriorVcov, PriorVcov, sigmasq, calcPosteriorVcov, PEV, nThreads)
}

cpp_optimal_cross_selection <- function(Crosses, fixedCrosses, nCross, targetAngle, u, ufixed, G, probMut = 0.01, nMutate = 2L, nSel = 500L, nPop = 10000L, maxGen = 1000L, maxRun = 100L, anglePenalty = 0.5, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_optimal_cross_selection`, Crosses, fixedCrosses, nCross, targetAngle, u, ufixed, G, probMut, nMutate, nSel, nPop, maxGen, maxRun, anglePenalty, nThreads)
}

