# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calculate_covariance_allier <- function(Crosses, genMap, M, U, t, intensity, covariance = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_allier`, Crosses, genMap, M, U, t, intensity, covariance, nThreads)
}

cpp_calculate_covariance_lehermeier <- function(Crosses, genMap, M, U, t, intensity, covariance = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_lehermeier`, Crosses, genMap, M, U, t, intensity, covariance, nThreads)
}

cpp_calculate_covariance_osthushenrich <- function(Crosses, genMap, M, U, t, intensity, covariance = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_osthushenrich`, Crosses, genMap, M, U, t, intensity, covariance, nThreads)
}

cpp_calculate_covariance_wolfe <- function(Crosses, genMap, Hap1, Hap2, U, D, intensity, covariance = FALSE, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calculate_covariance_wolfe`, Crosses, genMap, Hap1, Hap2, U, D, intensity, covariance, nThreads)
}

cpp_calcOHV <- function(Crosses, HBlocks, M, mu_vec, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_calcOHV`, Crosses, HBlocks, M, mu_vec, nThreads)
}

cpp_u_from_from_g <- function(M, G, g, scalingFactor, tol = 1e-10, LDvar = FALSE, Grouping = NULL, calcPriorVcov = FALSE, PriorVcov = NULL, sigmasq = NULL, calcPosteriorVcov = FALSE, PEV = NULL, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_u_from_from_g`, M, G, g, scalingFactor, tol, LDvar, Grouping, calcPriorVcov, PriorVcov, sigmasq, calcPosteriorVcov, PEV, nThreads)
}

cpp_optimal_cross_selection <- function(nCross, targetAngle, u, G, probMut = 0.01, nMutate = 2L, nSel = 500L, nPop = 10000L, maxGen = 1000L, maxRun = 100L, anglePenalty = 0.5, nThreads = 4L) {
    .Call(`_CrossingTools_cpp_optimal_cross_selection`, nCross, targetAngle, u, G, probMut, nMutate, nSel, nPop, maxGen, maxRun, anglePenalty, nThreads)
}

